Repository DivideE-ConqueR/confessions-client, pull requests merged in 2022-11, with the labels that each got.

#30 404 page
  public/index.html
  src/App.js
  src/pages/404.js
  tailwind.config.js
Labels: enhancement, good first issue, dev

#41 Update README.md
  README.md
Labels: documentation, good first issue, dev

#42 Report-post
  src/components/Card.js
  src/components/Report.js
  src/context/postContext.js
  src/pages/post.js
  src/utils/localStorage.js
Labels: enhancement, help wanted, dev

#43 Fix sync
  src/components/Report.js
  src/context/postContext.js
  src/hooks/useInterval.js
Labels: enhancement, help wanted, dev

#51 React Query
  src/App.js
Labels: bug, enhancement, dev

#52 Prettier code formatting
  .github/workflows/nodejs-ci.yml
  .husky/common.sh
  .husky/pre-commit
  .prettierrc.json
  package.json
  src/api/axios.js
  src/api/services/comment.js
  src/api/services/ip.js
  src/api/services/post.js
  src/api/services/sync.js
  src/components/Card.js
  src/components/Comment.js
  src/components/CustomAlert.js
  src/components/ErrorFallback.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Input.js
  src/components/Loader.js
  src/components/Report.js
  src/config/nanoid.js
  src/context/alertContext.js
  src/hooks/useAlert.js
  src/hooks/useInterval.js
  src/pages/404.js
  src/pages/home.js
  src/pages/new.js
  src/pages/post.js
  src/styles/index.css
  src/utils/error.js
  yarn.lock
Labels: enhancement, good first issue, dev

#53 Rename directory
  src/App.js
  src/lib/nanoid.js
Labels: good first issue, dev

#54 Search
  src/App.js
  src/components/Header.js
  src/pages/search.js
Labels: enhancement, good first issue, dev

#60 bump deps
  package.json
  yarn.lock
Labels: dependencies
