Repository DivideE-ConqueR/confessions-client, pull requests merged in 2022-09, with the labels that each got.

#4 Like Share Components Added
  package.json
  src/components/Card.js
  src/components/Feed.js
  yarn.lock
Labels: enhancement, good first issue

#5 Dislike Button Added
  src/components/Card.js
Labels: enhancement, good first issue

#7 Minor change
  src/components/Navbar.js
Labels: enhancement, good first issue

#9 Create LICENSE
  LICENSE
Labels: good first issue

#11 Add success or error alert
  package.json
  src/pages/new.js
  yarn.lock
Labels: enhancement

#12 Push to dev branch
  .gitignore
  package.json
  src/App.js
  src/api/base.js
  src/components/Card.js
  src/components/Feed.js
  src/components/Navbar.js
  src/index.js
  src/pages/home.js
  src/pages/new.js
  yarn.lock
Labels: enhancement, dev

#13 Finish Newpost
  package.json
  src/components/Card.js
  src/pages/home.js
  src/pages/new.js
  yarn.lock
Labels: enhancement

#14 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement, good first issue, dependencies
